### ISSUE TITLE
Improve README.md documents

### ISSUE THREAD

**Issue by kazydek** [kyma-incubator/marketplaces#13]
**Description**

Improve `README.md` documents in the whole repository - they were prepared for the 1.2 release in a quite limited form and size and may require improvement.
Consult @michal-hudy for input.

**Comment by hudymi** [comment]
As we are not working actively on support for GCP Marketplace, I'm going to close this issue. We will rather focus on improvements related to Kyma installation, so probably the marketplace will be not needed. Also, the new WG around installation has started recently 😄
