### ISSUE TITLE
Extend GCP app configuration with option to provide installation overrides

### ISSUE THREAD

**Issue by derberg** [kyma-incubator/marketplaces#4]
**Description**

- Have a large text box where you can baste the configmap and secrets that override installation values

**Reasons**

Enable flexible installation of kyma with specific overrides of values.yamls of components

**Attachments**

<img width="447" alt="Screen Shot 2019-06-03 at 21 27 40" src="https://user-images.githubusercontent.com/6995927/58828880-bb512200-8646-11e9-8b67-663dd70c0d51.png">

**Comment by hudymi** [comment]
As we are not working actively on support for GCP Marketplace, I'm going to close this issue. We will rather focus on improvements related to Kyma installation, so probably the marketplace will be not needed. Also, the new WG around installation has started recently 😄
