### ISSUE TITLE
[Blocked] Fully automate publishing of latest version of Kyma to marketplace

### ISSUE THREAD

**Issue by derberg** [kyma-incubator/marketplaces#5]
This is blocked for now as this is not fully supported by GC Marketplace. For now we managed to automate creation of image with deployer and licences generator

**Description**

- Have automation based on CI with typical approvals flows basen on Prow
- Make sure anyone can make a PR with changes that later will be reflected in marketplace

**Reasons**

For now publishing is possible if you have access to special GC project where there are more solutions. We do not want to give access there for to many users and we should make everything possible to modify through CIs and configuration/documentation files in repository

**Comment by hudymi** [comment]
As we are not working actively on support for GCP Marketplace, I'm going to close this issue. We will rather focus on improvements related to Kyma installation, so probably the marketplace will be not needed. Also, the new WG around installation has started recently 😄
