### ISSUE TITLE
[Blocked] Uninstallation triggering

### ISSUE THREAD

**Issue by derberg** [kyma-incubator/marketplaces#6]
This is blocked for now by https://github.com/kyma-project/kyma/issues/2942 and https://github.com/kyma-project/kyma/issues/4340

**Description**

- Uninstallation of Kyma application should uninstall whole Kyma
- Trigger proper mode of installation operator

**Reasons**

At the moment uninstallation of Application only removes deployer. Kyma is installed by separate operator and marketplace deployer only installs the operator. We should not only enable installation but also enable clear installation of Kyma.

**Comment by atakanyenel** [comment]
When an application is deleted by the GCP ui , it only deletes the resources that are in the namespace with the created application. (AFAIK) That's only the initial deployment job. Either a hook can be created that labels installation with uninstall when the job is deleted, and kyma runs the normal process or we wait for Google to implement a custom delete operation.

**Comment by derberg** [comment]
the installer supports now full uninstallation, it is now just a matter to use it in the marketplace

**Comment by hudymi** [comment]
As we are not working actively on support for GCP Marketplace, I'm going to close this issue. We will rather focus on improvements related to Kyma installation, so probably the marketplace will be not needed. Also, the new WG around installation has started recently 😄
